version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:12.18.2
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
  deploy:
    machine: true
    environment:
      HEROKU_APP_NAME: 'maumau-io' # define env var $HEROKU_APP
    steps:
      - checkout
      - heroku/install
      - heroku/check-authentication
      - run: docker build -t maumau/app:$CIRCLE_BRANCH .
      - run:
          name: Build and push a docker image
          description: Replacement of orb command heroku/push-docker-image because of its syntax error
          command: |
            heroku container:login
            heroku container:push -a $HEROKU_APP_NAME web
      - run:
          name: Release docker container
          description: Release container on Heroku
          command: |
            heroku container:release -a $HEROKU_APP_NAME web

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy
orbs:
  heroku: circleci/heroku@1.2.2
