export enum ActionType {
  PLAY_REGULAR_CARD = 'PLAY_REGULAR_CARD',
  PLAY_EIGHT = 'PLAY_EIGHT',
  PLAY_SEVEN = 'PLAY_SEVEN',
  PLAY_JACK = 'PLAY_JACK',
  KANNET_AND_DRAW = 'KANNET_AND_DRAW',
  KANNET = 'KANNET',
  ACCEPT_PENDING_SEVENS = 'ACCEPT_PENDING_SEVENS',
  END_GAME = 'END_GAME',
}
